### PR TITLE
ENH OSX SDK versions

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Addresses https://github.com/conda-forge/conda-forge.github.io/issues/891

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
It appears the preprocessor is being run when stuff is getting installed on osx. 

Do any of @conda-forge/openmpi have ideas here?

**Comment by minrk** [comment]
@beckermr I think this'll work after a rebase now that #46 has been merged

**Comment by beckermr** [comment]
This can be closed since the recipe now supports 10.9.

**Pull request closed without merging**
