### PR TITLE
Change maintainer username from @astrofrog-conda-forge to @astrofrog

### PR DESCRIPTION
**Pull request by astrofrog**
This is to update my username from @astrofrog-conda-forge to @astrofrog - I used to have a separate username back when being a member of any conda-forge repository meant that I saw all conda-forge repositories on Travis CI but this is no longer relevant.

@conda-forge-admin please rerender

### CODE REVIEW

**Review by beckermr — CHANGES_REQUESTED** [review]
Please use the admin command to add your new username. It will avoid the rerender and extra build on merge.

https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

**Comment by astrofrog** [comment]
@beckermr - is there a way to remove a username using a similar mechanism? Does ``please remove user ...`` work? (as I need to remove @astrofrog-conda-forge)

**Comment by beckermr** [comment]
I'd edit the bot pr it makes by hand using your old account and then merge.

**Comment by astrofrog** [comment]
Ok thanks!

**Pull request closed without merging**
