### PR TITLE
Add workarounds for OS X

### PR DESCRIPTION
**Pull request by leofang**
~~DO NOT MERGE until the ppc64le issue is resolved.~~ 

Added two workarounds for 
- open-mpi/ompi#7516
- open-mpi/ompi#5798

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
DO NOT MERGE until the ppc64le issue is resolved.

**Comment by leofang** [comment]
Moving the discussion for the failing ppc64le build to here:

> IDK about the ppce64le build. Is it enabled in the conda-forge.yaml and did the CI run on this PR?

@beckermr: Yes, it's enabled and the travis CI did run successfully. I am looking at the logs at https://travis-ci.com/github/conda-forge/openmpi-feedstock/pull_requests but didn't find anything suspicious (yet). We haven't been able to upload the ppc64le package two PRs in a row (#56 and #57).

**Comment by leofang** [comment]
@dalcinl It seems the PMIX error on OS X is silenced, but we still got this error (also seen in the previous PR):

> A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.
> Local host:  Mac-1354.local
  System call: unlink(2) /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//ompi.Mac-1354.501/pid.86722/1/vader_segment.Mac-1354.f4ec0001.2
  Error:       No such file or directory (errno 2)

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=141656&view=logs&j=ce7cbaa7-582c-5570-40f4-267b3d85fc9f&t=4a56039b-7269-50ae-de7a-538e91e6de06&l=16943

**Comment by leofang** [comment]
> We haven't been able to upload the ppc64le package two PRs in a row (#56 and #57).

@conda-forge/core It seems #57 has an error log here: 
https://travis-ci.com/github/conda-forge/openmpi-feedstock/builds/159126568#L188
Any idea what's that for? Don't see any error log for #56, though.

**Comment by leofang** [comment]
Let me correct my mistake 🤦🏻‍♂️ For #56 the missing package is for aarch64, not ppc64le...

**Comment by leofang** [comment]
Did someone re-triggered the ppc64le build? It just got uploaded, so we're good! The only issue left is the OS X error https://github.com/conda-forge/openmpi-feedstock/pull/58#issuecomment-611038365.

**Comment by leofang** [comment]
Just curious if it's reproducible...
@conda-forge-admin, please restart ci

**Comment by leofang** [comment]
Found a few pointers to the OS X shared memory unlink error (https://github.com/conda-forge/openmpi-feedstock/pull/58#issuecomment-611038365):
open-mpi/ompi#6518
open-mpi/ompi#5798
https://github.com/microsoft/azure-pipelines-image-generation/issues/932
https://www.mail-archive.com/devel@lists.open-mpi.org/msg20760.html
Seems like an old issue that should have been resolved long time ago...

@jsquyres @rhc54 do we hit the same bug or a new one?

**Comment by leofang** [comment]
After this run finishes, I'll test this workaround: https://github.com/open-mpi/ompi/issues/5798#issuecomment-426271555.

**Comment by leofang** [comment]
OK the CI finishes. The unlink error is "kinda" reproducible: It always happened in the recent CI runs on OS X, but in which tests it happened is random. Will apply the mentioned workaround now...

**Comment by leofang** [comment]
Just checked further the CI logs, and I found the OS X shared memory unlink error has been there as early as v4.0.1, so it's no new.

**Comment by leofang** [comment]
Looks like 1d93d46 works to silence the unlink error. Running again for one more data point...

@conda-forge-admin, please restart ci

**Comment by leofang** [comment]
Another run finished without any error. @dalcinl comments?

**Comment by rhc54** [comment]
Only one caution: in the last few OS-X major release series, the absolute path of `/tmp` has become a rather long string. Once we add our session directory path to it, we sometimes find that the string extends beyond the max allowed pathname length. We have therefore taken to advising Mac users to create their own `tmp` directory under their home directory, and to point OMPI to that as the tmpdir to use.

**Comment by dalcinl** [comment]
@leofang LGTM, I'll leave it on your hands.

**Pull request merged**
