### PR TITLE
Rerender for v10 gcc compilers

### LINKED ISSUE #91: {{mpi}}-mpicc not for use in recipes ?
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
In https://github.com/conda-forge/staged-recipes/pull/14726, the linux build cannot resolve dependencies in the build environment:
```
conda create -n test gcc_linux-64=10 gxx_linux-64=10 gfortran_linux-64=10 openmpi-mpifort
```
The resolution error is:
```
Package gfortran_linux-64 conflicts for:
openmpi-mpifort -> gfortran_linux-64[version='7.*|9.*|7.3.0.*']
gfortran_linux-64=10
```
Conda forge pinnings current show that [fortran compiler version should be 10.](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/56260d435c4d869432900d3641855cf45e7d62f1/recipe/conda_build_config.yaml#L38)

So why is this package still depending on versions 7,9? Is there a reason or just the package needs to be rerendered?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : base
    active env location : /home/dching/miniconda3
            shell level : 1
       user config file : /home/dching/.condarc
 populated config files : /home/dching/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.8.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.13.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/dching/miniconda3  (writable)
      conda av data dir : /home/dching/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dching/miniconda3/pkgs
                          /home/dching/.conda/pkgs
       envs directories : /home/dching/miniconda3/envs
                          /home/dching/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.8.8 Linux/5.13.0-30-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by carterbox**
The purpose of this PR is to get the openmpi-mpifort package built against the v10 fortran compiler.

There are a few possible approaches:
1. Update CUDA compiler to 11.1 from 10.2, so the host compiler moves from gcc=7 to gcc=10.
3. Enable a non-cuda build, which automatically tracks the current compiler pinnings.
4. ~~Relax compiler constraints so package built with gcc=7 can be used by gcc=10~~

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #91

### CODE REVIEW

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Review by leofang — CHANGES_REQUESTED** [review]
Let's discuss in #91.

**Comment by carterbox** [comment]
@conda-forge-admin please rerender

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by carterbox** [comment]
```
The following NEW packages will be INSTALLED:

    clang:          13.0.1-h694c41f_0         conda-forge
    clang-13:       13.0.1-default_he082bbe_0 conda-forge
    libclang-cpp13: 13.0.1-default_he082bbe_0 conda-forge
    libcxx:         12.0.1-habf9029_1         conda-forge
    libgfortran:    5.0.0-9_3_0_h6c81a4c_23   conda-forge
    libgfortran5:   9.3.0-h6c81a4c_23         conda-forge
    libllvm13:      13.0.1-h64f94b2_2         conda-forge
    libzlib:        1.2.11-h9173be1_1013      conda-forge
    llvm-openmp:    13.0.1-hcb1a161_1         conda-forge
    mpi:            1.0-openmpi               conda-forge
    openmpi:        4.1.2-h4ff0e22_1          local      
    openmpi-mpicc:  4.1.2-h5eb16cf_1          local      
    zlib:           1.2.11-h9173be1_1013      conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/Users/runner/miniforge3/conda-bld/openmpi-mpi_1646695176261/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
export SRC_DIR=/Users/runner/miniforge3/conda-bld/openmpi-mpi_1646695176261/test_tmp
+ export OMPI_MCA_plm=isolated
+ OMPI_MCA_plm=isolated
+ export OMPI_MCA_btl_vader_single_copy_mechanism=none
+ OMPI_MCA_btl_vader_single_copy_mechanism=none
+ export OMPI_MCA_rmaps_base_oversubscribe=yes
+ OMPI_MCA_rmaps_base_oversubscribe=yes
+ MPIEXEC=/Users/runner/miniforge3/conda-bld/openmpi-mpi_1646695176261/test_tmp/mpiexec.sh
+ pushd tests
+ [[ openmpi-mpicc == \o\p\e\n\m\p\i ]]
+ [[ openmpi-mpicc == \o\p\e\n\m\p\i\-\m\p\i\c\c ]]
+ command -v mpicc
+ mpicc -show
~/miniforge3/conda-bld/openmpi-mpi_1646695176261/test_tmp/tests ~/miniforge3/conda-bld/openmpi-mpi_1646695176261/test_tmp
$PREFIX/bin/mpicc
x86_64-apple-darwin13.4.0-clang -I$PREFIX/include -I$PREFIX/include -L$PREFIX/lib -L$PREFIX/lib -Wl,-rpath,$PREFIX/lib -lmpi
+ mpicc helloworld.c -o helloworld_c
--------------------------------------------------------------------------
The Open MPI wrapper compiler was unable to find the specified compiler
x86_64-apple-darwin13.4.0-clang in your PATH.

Note that this compiler was either specified at configure time or in
one of several possible environment variables.
```

OSXx64 does not like mismatched compiler.

**Comment by carterbox** [comment]
No rerender needed.

**Comment by leofang** [comment]
@carterbox If it helps, maybe we wanna try bumping the CUDA version (which is zipped with the compiler versions)? We chose 10.2 as the lowest common denominator supported in CF, but there's no real reason to stick to it.

**Comment by carterbox** [comment]
@leofang, We would need to bump the CUDA version to 11.1, then I think it would solve the problem because the compiler versions of no-CUDA and CUDA would match.

However, I really think having a separate no-CUDA and CUDA build is the simplest for maintenance because you don't have to think about whether the compilers match AND the CUDA compiler can be the lowest common denominator.

Lemme know what you want.

**Review by leofang — CHANGES_REQUESTED** [review]
Thanks @carterbox for giving it a try... Looks like there are too many obstacles ahead, and your original attempt (of a simple rebuild) was the best workaround 😞

The current implementation is not OK because it defeats all designs put in. Also, it'd confuse the solver as this is not how a cpu/gpu package should be built. Let's just revert to the original commit (where you bumped the build number). 

Sorry again for the time wasted...

**Comment by carterbox** [comment]
My original attempt (stopping with https://github.com/conda-forge/openmpi-feedstock/pull/92/commits/04fd665b88f0a5f75e0c64f1297a8763348d7728) doesn't do anything useful because, as I tried to explain, there is currently only one linux build and it uses gcc=7 instead of gcc=10. Rerendering doesn't change anything because the gcc version is locked to the cuda version.

I will use the approach https://github.com/conda-forge/openmpi-feedstock/issues/91#issuecomment-1062615457 where we just don't use the openmpi-mpicc/fortran metapackages in recipes.

**Pull request closed without merging**
