### PR TITLE
Fix CUDA awareness 

### LINKED ISSUE #83: CUDA awareness is not built in 4.1.0
Something might go wrong in the recent recipe updates. I can't get mpi4py's GPU example pass:
```
$ OMPI_MCA_opal_cuda_support=true  mpirun -n 2 python demo/cuda-aware-mpi/use_cupy.py 
--------------------------------------------------------------------------
The user requested CUDA support with the --mca mpi_cuda_support 1 flag
but the library was not compiled with any support.
--------------------------------------------------------------------------
[WCS-164320:29458] *** Process received signal ***
[WCS-164320:29458] Signal: Segmentation fault (11)
[WCS-164320:29458] Signal code: Address not mapped (1)
[WCS-164320:29458] Failing at address: (nil)
[WCS-164320:29458] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x128a0)[0x7f596b2dd8a0]
[WCS-164320:29458] *** End of error message ***
--------------------------------------------------------------------------
The user requested CUDA support with the --mca mpi_cuda_support 1 flag
but the library was not compiled with any support.
--------------------------------------------------------------------------
[WCS-164320:29459] *** Process received signal ***
[WCS-164320:29459] Signal: Segmentation fault (11)
[WCS-164320:29459] Signal code: Address not mapped (1)
[WCS-164320:29459] Failing at address: (nil)
[WCS-164320:29459] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x128a0)[0x7f84ec4898a0]
[WCS-164320:29459] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node WCS-164320 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```

Environment:
```
$ conda list
# packages in environment at /home/leofang/miniconda3/envs/mpi4py_dev:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
binutils_impl_linux-64    2.35.1               h193b22a_2    conda-forge
binutils_linux-64         2.35                h67ddf6f_30    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cudatoolkit               11.2.1               h8204236_8    conda-forge
cudnn                     8.1.0.77             h90431f1_0    conda-forge
cupy                      8.5.0            py38h69dedff_1    conda-forge
cutensor                  1.2.2.5              h96e36e3_3    conda-forge
cython                    0.29.22          py38h709712a_0    conda-forge
fastrlock                 0.6              py38h709712a_0    conda-forge
gcc_impl_linux-64         9.3.0               h70c0ae5_18    conda-forge
gcc_linux-64              9.3.0               hf25ea35_30    conda-forge
kernel-headers_linux-64   2.6.32              h77966d4_13    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-devel_linux-64     9.3.0               h7864c58_18    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.1.0a0                  pypi_0    pypi
nccl                      2.8.4.1              hdc17891_3    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.20.1           py38h18fd61f_0    conda-forge
openmpi                   4.1.0                hbfc84c5_3    conda-forge
openmpi-mpicc             4.1.0                h7f98852_3    conda-forge
openssl                   1.1.1j               h7f98852_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
python                    3.8.8           hffdb5ce_0_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
sqlite                    3.35.2               h74cdb3f_0    conda-forge
sysroot_linux-64          2.12                h77966d4_13    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Close #83. Fix a silly mistake that I made in #80...😞

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Should the `run_constrained` in `meta.yaml` also be updated?

**Comment by leofang** [comment]
> Should the `run_constrained` in `meta.yaml` also be updated?

No, because we can support any CUDA version. Open MPI does not care. I set it to 9.2 only because it's the oldest version available on CF.

**Comment by jakirkham** [comment]
Ok didn't know if we would run into issues since we are actually building against CUDA 10.2

**Comment by leofang** [comment]
Right, we made sure of that earlier. Open MPI does not rely on any CUDA runtime API, only driver ones. It dlopen `libcuda.so` at runtime. It has been the case since CUDA 6 (?). There are some weird CUDA version check at build time that should have been removed (https://github.com/open-mpi/ompi/issues/7334).

**Comment by leofang** [comment]
Travis is dead 😞

@conda-forge-admin please restart ci

**Comment by leofang** [comment]
osx segfaults...?

**Comment by leofang** [comment]
@conda-forge-admin please restart ci

**Comment by leofang** [comment]
I manually restarted Travis, but if it fails the 3rd time, I will merge anyway. It's been in a poor state in weeks and not getting any better: https://gitter.im/conda-forge-ppc64le/Lobby

**Comment by leofang** [comment]
...and it failed again as I typed.

**Comment by leofang** [comment]
Merging, and will restart manually until the package is out, although the `ppc64le` package built on Travis is not impacted by my silly mistake, so it's fine to not upload a new one. In the near future let's look for other alternatives, maybe cross-compiling?

**Comment by leofang** [comment]
> Merging, and will restart manually until the package is out

The merge commit built succesfully.

**Comment by jakirkham** [comment]
Sorry for missing this before, but should these lines have been updated to CUDA 10.2 as well?

https://github.com/conda-forge/openmpi-feedstock/blob/fde85a81ef3e94a6714d4227e9968e59da19300e/recipe/meta.yaml#L47-L48

**Pull request merged**
