### PR TITLE
OSX: No Min Version

### PR DESCRIPTION
**Pull request by ax3l**
Try to remove the minimum version requiring OSX 10.12+. Let's see if this works with newer versions of OpenMPI 4 and we can broaden the scope of supported OSX versions again.

Could depend on #46, might be related to #49 .

cc @minrk @isuruf 

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
Looks like this `clock_gettime` requirement was removed in 4.0.2.

**Comment by ax3l** [comment]
Nice, will rebase after #46 is merged :)

**Comment by ax3l** [comment]
Oh wait, you integrated that already in #46 :)

**Pull request closed without merging**
