### PR TITLE
Migrate `sysroot_*` to `{{ stdlib('c') }}`

### PR DESCRIPTION
**Pull request by jakirkham**
Follows up on this suggestion ( https://github.com/conda-forge/openmpi-feedstock/pull/147#pullrequestreview-1984041142 ), to align with broader move away from `sysroot_*` to `{{ stdlib('c') }}` ( https://github.com/conda-forge/conda-forge.github.io/issues/2102 )

cc @beckermr

<hr>

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Review by h-vetinari — APPROVED** [review]
This LGTM (though not a maintainer here) - thanks for doing this!

(not sure why it's a draft...)

**Comment by jakirkham** [comment]
Thanks Axel! 🙏

Was looking for reviews from folks like yourself 🙂

**Comment by dalcinl** [comment]
@jakirkham Looks like this one is ready. Should we merge?

**Comment by jakirkham** [comment]
If it looks good, please feel free to merge

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
